# Site settings
title: Arguggi
email: arguggi@arguggi.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Wut?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "arguggi.co.uk" # the base hostname & protocol for your site
github_username:  arguggi

# Build settings
markdown: kramdown

permalink: /blog/:title
