# Site settings
title: "Arguggi"
email: "arguggi@arguggi.co.uk"
description: > # this means to ignore newlines until "baseurl:"
  Wut?
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://arguggi.co.uk" # the base hostname & protocol for your site
github_username:  "arguggi"

permalink: /:title

# When testing in local setting do not add comments or tracking
production: False

# Build settings
markdown: kramdown

author:
  name : "Arguggi"
  email: "arguggi@arguggi.co.uk"

atom_feed: "/atom.xml"
rss_feed: "/rss.xml"
